[package]
name = "tiefdownconverter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.4", features = ["derive"] }
copy_dir = "0.1.3"
regex = "1.11.1"
toml = "0.8.20"
