[package]
name = "tiefdownconverter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.4", features = ["derive"] }
color-eyre = "0.6.3"
copy_dir = "0.1.3"
pandoc = "0.8.11"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
