.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH validate 1  "validate " 
.SH NAME
validate \- Validate the TiefDown project structure and metadata.
.SH SYNOPSIS
\fBvalidate\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Validate the TiefDown project structure and metadata.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
