.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH update 1  "update " 
.SH NAME
update \- Update a markdown project in the project.
.SH SYNOPSIS
\fBupdate\fR [\fB\-\-path\fR] [\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Update a markdown project in the project.
.SH OPTIONS
.TP
\fB\-\-path\fR=\fIPATH\fR
The path to the markdown project.
.TP
\fB\-\-output\fR=\fIOUTPUT\fR
The output folder.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
The name of the markdown project to update.
