.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH list-templates 1  "list-templates " 
.SH NAME
list\-templates \- List the templates in the project.
.SH SYNOPSIS
\fBlist\-templates\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List the templates in the project.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
