.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH add 1  "add " 
.SH NAME
add \- Add a new markdown project to the project.
.SH SYNOPSIS
\fBadd\fR <\fB\-\-path\fR> <\fB\-\-output\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Add a new markdown project to the project.
.SH OPTIONS
.TP
\fB\-\-path\fR=\fIPATH\fR
The path to the markdown project.
.TP
\fB\-\-output\fR=\fIOUTPUT\fR
The output folder.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
The name of the markdown project to create.
