.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH check-dependencies 1  "check-dependencies " 
.SH NAME
check\-dependencies \- Validate dependencies are installed.
.SH SYNOPSIS
\fBcheck\-dependencies\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Validate dependencies are installed.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
