.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH add 1  "add " 
.SH NAME
add \- Add a new template to the project.
.SH SYNOPSIS
\fBadd\fR [\fB\-f\fR|\fB\-\-template\-file\fR] [\fB\-t\fR|\fB\-\-template\-type\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-\-filters\fR] [\fB\-\-preprocessor\fR] [\fB\-\-processor\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Add a new template to the project.
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-template\-file\fR=\fITEMPLATE_FILE\fR
The file to use as the template. If not provided, the template name will be used.
.TP
\fB\-t\fR, \fB\-\-template\-type\fR=\fITEMPLATE_TYPE\fR
The type of the template. If not provided, the type will be inferred from the template file.
.br

.br
[\fIpossible values: \fRtex, typst, epub, custom\-pandoc]
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIOUTPUT\fR
The output file. If not provided, the template name will be used.
.TP
\fB\-\-filters\fR=\fIFILTERS\fR
The luafilters to use for pandoc conversion of this templates markdown.
.TP
\fB\-\-preprocessor\fR=\fIPREPROCESSOR\fR
The preprocessor to use for this template.
.TP
\fB\-\-processor\fR=\fIPROCESSOR\fR
The processor to use for this template.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
