name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Running debug Linux build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build

      - name: Package binary (Linux)
        run: |
          mkdir -p artifacts
          tar -czvf artifacts/tiefdownconverter-linux.tar.gz -C target/debug tiefdownconverter

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tiefdownconverter-linux
          path: artifacts/*
