name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (Linux & macOS)
        if: runner.os != 'Windows'
        run: cargo build --release

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Package binary (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p artifacts
          tar -czvf artifacts/tiefdownconverter-linux.tar.gz -C target/release tiefdownconverter

      - name: Package binary (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p artifacts
          tar -czvf artifacts/tiefdownconverter-macos.tar.gz -C target/release tiefdownconverter

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir artifacts
          Compress-Archive -Path target\x86_64-pc-windows-msvc\release\tiefdownconverter.exe -DestinationPath artifacts\tiefdownconverter-windows.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tiefdownconverter-${{ runner.os }}
          path: artifacts/*

  fetch-and-release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Determine Pre-release Status
        id: prerelease_check
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if [[ "$TAG_NAME" =~ ^v0\.|- ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Auto-generated release notes."
          draft: true
          prerelease: ${{ env.prerelease }}
          generate_release_notes: true
          files: artifacts/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
