name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install pandoc, texlive-xelatex and typst
        run: |
          apt-get update
          apt-get install -y pandoc texlive-xetex curl xz-utils
          curl -L -o typst.tar.xz https://github.com/typst/typst/releases/download/v0.13.1/typst-x86_64-unknown-linux-musl.tar.xz
          mkdir typst-bin
          tar -xf typst.tar.xz -C typst-bin --strip-components=1
        env:
          PATH: ${{ github.workspace }}/typst-bin:${{ env.PATH }}

      - name: Add typst-bin to PATH
        run: echo "${{ github.workspace }}/typst-bin" >> $GITHUB_PATH

      - name: Run tests
        run: cargo test --verbose
